### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by huseyinkarael** [HdriGFX/RizLRegister#1]
unfortunately not working

**Comment by HdriGFX** [comment]
firstly, you need to describe the issue. dont just say "not working". it irritates me and its a waste of my time. if the register function doesnt work its because you need to input new headers. and i have made a new tool that automatically makes a new header, but the source will not be given out. you need to change csrftoken, mid, and rur. bye

**Comment by mzaboss** [comment]
hi, great code, neat.. and awesome, i've tired to upgraded it with the new changes. but unfortunately i didn't successes.. still giving me blank console for some reasons. 

however, is it possible please to upgrade it to make it work or kindly can you send me a private repo please with the updated one? 

thank you in advance,
regards.

**Comment by huseyinkarael** [comment]
> hi, great code, neat.. and awesome, i've tired to upgraded it with the new changes. but unfortunately i didn't successes.. still giving me blank console for some reasons.
> 
> however, is it possible please to upgrade it to make it work or kindly can you send me a private repo please with the updated one?
> 
> thank you in advance,
> regards.

    private async Task InitializeSession()
    {
        using (HttpClientHandler handler = new HttpClientHandler() { CookieContainer = Cookies, UseCookies = true, AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate })
        using (HttpClient client = new HttpClient(handler))
        using (HttpRequestMessage request = new HttpRequestMessage() { Method = HttpMethod.Get, RequestUri = new Uri("https://i.instagram.com/") })
        {
            request.Headers.UserAgent.ParseAdd("Instagram 7.1.1 Android (21/5.0.2; 480dpi; 1080x1776; LGE/Google; Nexus 5; hammerhead; hammerhead; en_US)");
            request.Headers.Add("accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8");
            request.Headers.Add("accept-encoding", "gzip, deflate, sdch");
            request.Headers.Add("accept-language", "en-US,en;q=0.8");
            request.Headers.Add("upgrade-insecure-requests", "1");

            var response = await client.SendAsync(request);
            var responseString = await response.Content.ReadAsStringAsync();
        }
    }
 public async Task<string> CreateAccount(string Username, string First_Name, string Password, string Email)
    {
        try
        {
            await InitializeSession();

            var RegistrationContent = new
            {
                username = Username,
                first_name = First_Name,
                password = Password,
                guid = RandomString(8) + "-" + RandomString(4) + "-" + RandomString(4) + "-" + RandomString(4) + "-" + RandomString(12),
                email = Email,
                device_id = "android-" + HMAC(Random.Next(1000, 9999).ToString()).ToString().Substring(0, Math.Min(64, 16))
            };

            string Json = JsonConvert.SerializeObject(RegistrationContent, Formatting.Indented, new IsoDateTimeConverter());

            Dictionary<string, string> RegistrationRequest = new Dictionary<string, string>()
            {
                { "signed_body",  HMAC(Json) + "." + Json },
                { "ig_sig_key_version", "4" }
            };

            using (HttpClientHandler handler = new HttpClientHandler() { CookieContainer = Cookies, UseCookies = true, AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate })
            using (HttpClient client = new HttpClient(handler))
            using (HttpRequestMessage request = new HttpRequestMessage() { Method = HttpMethod.Post, RequestUri = new Uri("https://i.instagram.com/api/v1/accounts/create/"),
			
			Content = new FormUrlEncodedContent(RegistrationRequest) 
			
			})
            {
                request.Headers.Host = "i.instagram.com";
                request.Headers.UserAgent.ParseAdd("Instagram 7.1.1 Android (21/5.0.2; 480dpi; 1080x1776; LGE/Google; Nexus 5; hammerhead; hammerhead; en_US)");
                request.Headers.Add("Accept-Language", "en-US");
                request.Headers.Add("Accept-Encoding", "gzip");
                request.Headers.Add("Cookie2", "$Version=1");
                request.Headers.Add("X-IG-Connection-Type", "WIFI");
                request.Headers.Add("X-IG-Capabilities", "BQ==");

                var response = await client.SendAsync(request);
                var responseString = await response.Content.ReadAsStringAsync();
                
                JObject JS = JObject.Parse(responseString);

                if ((string)JS["status"] != "fail")
                {
                    if ((bool)JS["account_created"] == true)
                    {
                        return "Açıldı";
                      

                    }
                    else
                    {
                        if ((string)JS["errors"][" username"] != null)
                            return "Error: " + (string)JS["errors"]["username"];
                            
                        if ((string)JS["errors"]["password"] != null)
                            return "Error: " + (string)JS["errors"]["password"];

                        if ((string)JS["errors"]["email"] != null)
                            return "Error: " + (string)JS["errors"]["email"];

                        return "Boş Değer";
                    }
                }
                else
                {
                    if ((bool)JS["spam"] == true)
                        return "Spam";

                    return "Error: " + (string)JS["feedback_message"];
                }
            }
        }
        catch (Exception ex) { return "Error: " + ex.Message; }
    }

**Comment by huseyinkarael** [comment]
edit this code
